### ISSUE TITLE
GPS is tracking incorrectly with the KML and KML-Andro.Bats. 

### ISSUE THREAD

**Issue by PhantomDeep** [PCigales/Kml_from_photos#1] opened 2022-06-29 23:18 UTC
When I use the EXIF Info from Infran, it gives the accurate location on google earth. But when I use the batch, it's giving me a location in Russia Rather than Canada. I believe the longitude is to represent as "-113", but instead is batching as "113".

I've only just started this, but I can't seem to figure out if I've made a mistake with the process.

**Comment by PCigales** [comment] 2022-06-30 07:00
Thank you for reporting this issue. You are right, the script does not properly handle GPS coordinates at the left side of Greenwich meridian. I did not happen to use it with photos taken in this part of the world, so I did not notice that I had missed half of the planet !
I am going to fix this bug, it should not be too complicated.

**Comment by PCigales** [comment] 2022-06-30 12:53
The issue should be fixed.
Could you, please, check whether the batch now works as expected ?

**Comment by PhantomDeep** [comment] 2022-06-30 21:20
Going to restart the setup, it no longer wants to batch. I'll keep you posted. Very handy application you created though :). Can't seem to get it batching again, opens the KML.BAT prompt then closes.

**Comment by PCigales** [comment] 2022-07-01 06:41
I have made a small adjustment, could you please give it a try ?
If it does not work, to understand what is happening, I would need to know the exact command you used (or the process if you ran it from Windows explorer by dragging a folder or just double clicking it) and what messages you get.

**Comment by PhantomDeep** [comment] 2022-07-01 17:25
Hey! so, the first 1 or 2 attempts it didn't want to work initially. HOWEVER, the kml-andro.bat is working with double-click on the file, but not drag to the file. The kml-bat is processing the images with double-click but not drag and drop. The kml.bat is not generating a google earth file after processing the images.

Attached a capture of the success of batching from the kml-andro.bat. The initial issue is resolved :). The images aren't rendering into the pins though, and it's creating the large X box. Is there a way to adjust pin color?

I apologize if I'm causing a headache, I think this is a very cool idea.

![Capture](https://user-images.githubusercontent.com/108434581/176940573-eff61609-8015-4f31-8000-dc7dda11186d.PNG)

**Comment by PCigales** [comment] 2022-07-01 17:42
The kml file generated by kml-andro.bat is to be used with Google Earth on an Android phone, and your screenshot seems to be drawn from the desktop version.
For both batches, what is supposed to be dragged is a folder, not pictures. I tried again, and the scripts worked as expected either run from a cmd window wih the absolute path to the folder as argument, or from Windows explorer,  by dragging a folder containing pictures on the batch file or by placing it inside the folder and double clicking it. The thumbnails also appear on the pins.
I am afraid I cannot help you to solve your problem without further description of what you attempt and what happens, as I cannot reproduce the bug.

**Comment by PhantomDeep** [comment] 2022-07-01 23:26
The folder was the final trick, sorry about that! it's working great!!  Anywhere I can edit the thumbnail from the X though to a pin red/green etc pending on the folder? 

Your help has been awesome.

**Comment by PCigales** [comment] 2022-07-02 14:55
This is how the kml file generated by kml.bat is expected to be displayed in Google Earth Desktop (Windows), as for the pins and the balloon that is spawned when a pin is clicked:
![image](https://user-images.githubusercontent.com/58741513/177005434-daae6566-9fd3-456e-9be3-12c504a74594.png)
If you get a X instead of the thumbnail, it means that Google Earth does not manage to load the thumbnail (using the path defined inside the kml file through the \<Icon>\<href>file:///.............\</href>\</Icon> statement for each placemark).
In the folder in which the kml file is created, there should be a subfolder named "thumbs", containing all the thumbnails of the photos. If it is not the case, then something went wrong during the execution of the batch. You can edit the batch kml.bat and add at the end a line with the instruction "pause" (without the quote), so that when the batch is run, the window remains open, and you can copy all the messages and look for errors.

**Comment by PhantomDeep** [comment] 2022-07-02 17:09
The place you have posted above is beautiful! That pause was handy. I'm seeing its the i_view32

Scan de "C:\Users\Justin\AppData\LocalLow\Google\GoogleEarth\Test Pics\" pour création des miniatures dans "C:\Users\Justin\AppData\LocalLow\Google\GoogleEarth\Test Pics\thumbs\"
'"C:\Program Files (x86)\Irfanview\i_view32.exe"' is not recognized as an internal or external command,
operable program or batch file.

Hahaha :( , I changed the code for the script to account for by 64 bit. It's working!!

**Closed as completed** 2022-07-02 17:20 UTC
Labels: bug, good first issue
